---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/roles":
    get:
      summary: reads available roles
      tags:
      - Roles
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: blog found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
