default: &default
  bootstrap_servers:
    - b-1.echodev.tf55jh.c2.kafka.us-east-1.amazonaws.com:9096
    - b-2.echodev.tf55jh.c2.kafka.us-east-1.amazonaws.com:9096
    - b-3.echodev.tf55jh.c2.kafka.us-east-1.amazonaws.com:9096
  client_id: chesser_development
  sasl_username: sasl_username
  sasl_password: sasl_password
  default_consumer_group: chesser_development_consumer_group
  default_topic: development.partner_integrations.test

development:
  <<: *default
  bootstrap_servers:
    - b-1.echodev.tf55jh.c2.kafka.us-east-1.amazonaws.com:9096
    - b-2.echodev.tf55jh.c2.kafka.us-east-1.amazonaws.com:9096
    - b-3.echodev.tf55jh.c2.kafka.us-east-1.amazonaws.com:9096
  schema_registry: http://staging-echo-101:8000
  kafka_ui: http://staging-echo-102:9000

test:
  <<: *default

staging:
  <<: *default
  bootstrap_servers:
    - b-1.echononprod.t0pdea.c19.kafka.us-east-1.amazonaws.com:9096
    - b-2.echononprod.t0pdea.c19.kafka.us-east-1.amazonaws.com:9096
    - b-3.echononprod.t0pdea.c19.kafka.us-east-1.amazonaws.com:9096
  schema_registry: https://schema-registry-staging.justworks.tools
  kafka_ui: https://echo.nonprod.vibe.justworks.com

production:
  <<: *default
  bootstrap_servers:
    - b-1.echoprod.svocuy.c12.kafka.us-east-1.amazonaws.com:9096
    - b-2.echoprod.svocuy.c12.kafka.us-east-1.amazonaws.com:9096
    - b-3.echoprod.svocuy.c12.kafka.us-east-1.amazonaws.com:9096
  schema_registry: https://schema-registry-prod.justworks.tools
  kafka_ui: https://echo.prod.vibe.justworks.com

